spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quiz?characterEncoding=UTF-8
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
  main:
    allow-bean-definition-overriding: true
